### ISSUE TITLE
Add blurb to novels page

### ISSUE THREAD

**Issue by TwitchBronBron** [MadisonIlia/MadisonIlia.com#1]
Sometimes, even with the best intentions…the lines of justice and revenge get crossed.

Sophia Dimitri has the perfect life—a great husband, a beautiful toddler, and a job she loves. She and her husband, Luka, are undercover DEA agents based in Manhattan, New York. After Luka and their son, Niklaus, are killed in a freak car incident, Sophia quickly suspects foul play.

The case is abruptly closed, forcing Sophia and her partner Ace, to take matters into their own hands. Setting out to find justice for her family they begin looking for The Crow, a drug organization tied to a world they are not prepared for. A world where criminals hide behind badges, family ties don’t always mean blood, and people are rarely who they appear to be.

When emotions are intertwined with blinding pain, reason doesn’t enter the equation and everyone has the potential to become a ticking time bomb, bound to detonate without notice.

As the investigation comes full circle, the duo finds themselves in a fight for their lives…crossing invisible boundaries from which they can’t return.

**Comment by MadisonIlia** [comment]
Updated blurb ! 

Sometimes, even with the best intentions…the lines of justice and revenge get crossed.

Sophia Dimitri has the perfect life—a great husband, a beautiful toddler, and a job she loves. She and her husband, Luka, are undercover DEA agents based in Manhattan, New York. After Luka and their son, Niklaus, are killed in a freak car incident, Sophia quickly suspects foul play.

The case is abruptly closed, forcing Sophia and her partner, Ace, to take matters into their own hands. Setting out to find justice for her family they begin looking for The Crow, a drug organization tied to a world they are not equipped to navigate—a world where criminals hide behind badges, family ties don’t always mean blood, and people are rarely who they appear to be.

When emotions are intertwined with blinding pain, reason doesn’t enter the equation and everyone has the potential to become a ticking time bomb, bound to detonate without notice. 

As the investigation comes full circle, the duo finds themselves in a fight for their lives…crossing invisible boundaries from which they can never return.

**Comment by TwitchBronBron** [comment]
Added.
