### ISSUE TITLE
Open social pages in new window

### ISSUE THREAD

**Issue by MadisonIlia** [MadisonIlia/MadisonIlia.com#16]
Can we make it so a new window opens whenever they click on any of the social media links. I also Have a tiktok. Not sure if we should list that?

Same concept whenever I finally get my pre-order up and going!

**Comment by TwitchBronBron** [comment]
Yeah, give me your tictok link too. I'll add it. Is it an official tictok
or just your personal?

**Comment by MadisonIlia** [comment]
@TwitchBronBron official tiktok for Madison Ilia @madisonilia for tiktok

**Comment by MadisonIlia** [comment]
@TwitchBronBron I think my linkedin is under Madison Goodwin . . . and I'm not sure If I want to switch that to Madison Ilia or not yet. so just facebook instagram and tiktok
