### ISSUE TITLE
Font

### ISSUE THREAD

**Issue by MadisonIlia** [MadisonIlia/MadisonIlia.com#18]
Would it be possible to use a different font? Perhaps something similar to Times New Roman, more boxy style. If not no biggie,.

**Comment by TwitchBronBron** [comment]
Yep we can change the font. If you can, pick one from this list. They are the most compatible across all browsers and devices. If you can't find one you like, let me know and I'll show you a set of different fonts to choose from, but it makes the page load speed a little slower.

https://www.w3schools.com/cssref/css_websafe_fonts.asp

**Comment by TwitchBronBron** [comment]
Oh. And no cursive! 😁

**Comment by MadisonIlia** [comment]
@ Times New Roman I like best  I think out of that list .

**Comment by TwitchBronBron** [comment]
I changed it. I liked the previous font better, personally. But Give it a look, see what you think. 

Old:
![image](https://user-images.githubusercontent.com/2544493/151662312-3095f8bf-9e68-413f-9d68-b10f33c4ebb4.png)

New (Times New Roman):
![image](https://user-images.githubusercontent.com/2544493/151662324-8b43cbe8-dd61-456e-805d-609eb5d32be4.png)
