### ISSUE TITLE
Add link for Pre order!!!!

### ISSUE THREAD

**Issue by MadisonIlia** [MadisonIlia/MadisonIlia.com#23]
https://www.amazon.com/dp/B09RJPSP2M/ref=sr_1_1?crid=2T2YZJWVGDH05&keywords=The+Crow+MAdison+Ilia&qid=1643587283&sprefix=the+crow+madison+ilia%2Caps%2C143&sr=8-1

**Comment by TwitchBronBron** [comment]
I added the link to the following places:
- made the home page banner clickable
![image](https://user-images.githubusercontent.com/2544493/151783012-15f2e5be-059d-4d19-a021-c4866ced05fa.png)

- added a sentence on the home page
![image](https://user-images.githubusercontent.com/2544493/151783101-acab9918-b2fd-4e52-baa6-7c93c6c123b5.png)

- added a "pre-order now" button to the novels page.
![image](https://user-images.githubusercontent.com/2544493/151783153-7eb5fbe0-4b6a-4765-a448-0723b462da8e.png)

**Comment by MadisonIlia** [comment]
Thanks !
