### ISSUE TITLE
Site background

### ISSUE THREAD

**Issue by TwitchBronBron** [MadisonIlia/MadisonIlia.com#5]
I would like this to be the backdrop on all my pages. however. can you do like a grey overlay or something so the words wont be hard to see? I'm going to get you updated content. hopefully by tonight. 

Something like this: https://s3.amazonaws.com/roostery-composites/compost/5614146/fabric-preview-fq_0_l.jpg

**Comment by TwitchBronBron** [comment]
@MadisonIlia I don't really think we need to do this anymore, do we? If so, can you close this ticket?

**Comment by MadisonIlia** [comment]
@TwitchBronBron you can clear this portion. But I feel like a light grey would be less blinding than white. IF you think its ok just leave it for now.

**Comment by TwitchBronBron** [comment]
@MadisonIlia I darkened the background color slightly, from #FFFFF to #F9F9F9. Just for this screenshot, I left the footer as pure white so you can see the difference. Is that less blinding enough?

![image](https://user-images.githubusercontent.com/2544493/151699580-e0fb74f1-2255-44db-9c6f-f5ff5ee24507.png)

**Comment by MadisonIlia** [comment]
I love it !
